### ISSUE TITLE
License please

### ISSUE THREAD

**Issue by blag** [withoutboats/bpb#1]
Hi, I may have just missed it, but it seems that your project does not have a license.

When you choose a license, please consider allowing non-GPL software to link to yours. I think licensing your code under the LGPLv3 would be perfect for that, because it ensures that your code will get additions and improvements but people who can't legally link to it or use copyleft software can also at least incorporate your project into theirs. There's a tradeoff between helping everybody (including non-GPL software) to be secure and pushing the world to be completely open source.

**Comment by cfcs** [comment]
How about you start paying the vendors whose code you use in your proprietary solutions instead of begging for unilateral donations to your for-profit company?

If you **actually** care about the well-being of "everybody" you could even, you know, offer the author a support contract to make sure your users receive updates when issues are found.

**Comment by gmorenz** [comment]
Check `Cargo.toml`

> license = "MIT OR Apache-2.0"

**Comment by withoutboats** [comment]
@cfcs Aggressive comments like yours are not appreciated or welcome on my repositories. Its unacceptable to talk to a stranger in that tone when all they've done is express their opinions about licensing.

The license for this crate is listed in the Cargo.toml. I would merge a PR adding the license files, but won't bother doing it myself.
